name: "build-release-emscripten"
on:
  push:
  release:
  pull_request:
jobs:
  build:
    name: Emscriptem/WASM release build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          path: landstalker_engine
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: |
             sudo apt-get update
             sudo apt-get install -y \
                gcc-11 \
                g++-11 \
                cmake \
                libx11-dev \
                xserver-xorg-dev \
                xorg-dev \
                libwayland-server0 \
                libwayland-cursor0 \
                libwayland-client0

      - name: Checkout emsdk
        uses: actions/checkout@v5
        with:
          repository: emscripten-core/emsdk
          path: emsdk

      - name: Install emsdk
        working-directory: ${{github.workspace}}/emsdk
        run: |
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Configure
        working-directory: ${{github.workspace}}/landstalker_engine
        run: |
          source ../emsdk/emsdk_env.sh
          emcmake cmake -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}/landstalker_engine/build
        run: |
          source ../../emsdk/emsdk_env.sh
          emmake make -j8

      - name: Compress artifacts
        working-directory: ${{github.workspace}}/landstalker_engine/build
        shell: bash
        run: tar zvcf landstalker_engine_emscripten.tar.gz dds520.wasm dds520.js dds520.html

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landstalker_engine_binary_emscripten
          path: ${{github.workspace}}/landstalker_engine/build/landstalker_engine_emscripten.tar.gz

      - name: Copy artifacts to root
        working-directory: ${{github.workspace}}/
        run: |
          mkdir html
          cp ${{github.workspace}}/landstalker_engine/build/dds520.html html/index.html
          cp ${{github.workspace}}/landstalker_engine/build/dds520.{js,wasm} html

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/html

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Publish page (master)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.extract_branch.outputs.branch == 'master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/html

      - name: Publish page (branch)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/html
          destination_dir: ./${{ steps.extract_branch.outputs.branch }}

      - name: Publish page (PR)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/html
          destination_dir: PR-${{ github.event.number }}

      - name: Update comment
        uses: hasura/comment-progress@v2.2.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "A preview of ${{ github.event.after }} is uploaded and can be seen here:\n\n ✨ https://lordmir.github.io/landstalker_engine/${{ github.event.number }} ✨\n\nChanges may take a few minutes to propagate."
