name: "build-release-ubuntu"
on:
  push:
  release:
    types: [published]
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: master
jobs:
  build:
    name: Ubuntu release build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          path: landstalker_engine
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: |
             sudo apt-get update
             sudo apt-get install -y \
                gcc-11 \
                g++-11 \
                cmake \
                libx11-dev \
                xserver-xorg-dev \
                xorg-dev \
                libwayland-server0 \
                libwayland-cursor0 \
                libwayland-client0

      - name: 'Configure'
        working-directory: ${{github.workspace}}/landstalker_engine
        run: |
          cmake -S . -B build

      - name: 'Build Release'
        working-directory: ${{github.workspace}}/landstalker_engine
        run: |
          cmake -S . -B build -DLANDSTALKER_BUILD_SHARED=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j32
          cmake --install build --prefix ./release

      - name: 'Build Debug'
        working-directory: ${{github.workspace}}/landstalker_engine
        run: |
          cmake -S . -B build_debug -DLANDSTALKER_BUILD_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_debug -j32
          cmake --install build_debug --prefix ./debug

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landstalker_engine_binary_ubuntu
          path: |
            ${{github.workspace}}/landstalker_engine/release
            ${{github.workspace}}/landstalker_engine/debug
